### PR TITLE
Update to 1.8.1

### PR DESCRIPTION
**Pull request by nicolasfella**

### CODE REVIEW

**Comment by nicolasfella** [comment]
> ```
> flatpak run --env=G_DEBUG=fatal-criticals --command=appstream-util org.flatpak.Builder validate builddir/*/share/appdata/org.kde.ruqola.appdata.xml
>  in dir /srv/buildbot/worker/build-x86_64-5/build (timeout 1200 secs)
>  watching logfiles {}
>  argv: b'flatpak run --env=G_DEBUG=fatal-criticals --command=appstream-util org.flatpak.Builder validate builddir/*/share/appdata/org.kde.ruqola.appdata.xml'
>  using PTY: False
> builddir/files/share/appdata/org.kde.ruqola.appdata.xml: FAILED:
> • style-invalid         : Content before <ul> is too short [15], at least 20 characters required
> Validation of files failed
> program finished with exit code 1
> ```

I really don't want to change the metadata to appease some arbitrary pedantic check that thinks my sentence is 5 characters too short

**Comment by travier** [comment]
@hfiguiere Do you know how we can skip this check? I can not find it in https://github.com/flathub/flathub/wiki/App-Maintenance#flathubjson

**Comment by travier** [comment]
I understand it's a bit arbitrary but fixing it this way might be the easiest way

**Comment by hfiguiere** [comment]
It passed before.

**Comment by tsdgeos** [comment]
> It passed before.

So what? The requirement is totally arbitrary. Make it go away.

**Comment by tsdgeos** [comment]
Because seriously, see https://apps.kde.org/ruqola/ my guess is that the checker is complaining about the "Extra features:" text? (the only one i can find of 15 chars length)

*WHY ON EARTH* would anyone complain about that text

**Comment by travier** [comment]
Technically it's appstream-util (likely from https://github.com/hughsie/appstream-glib) complaining :/

**Comment by travier** [comment]
@barthalion Is there an option to use the relaxed mode: `appstream-util validate-relax`?

**Comment by barthalion** [comment]
You can submit an exception about skip-appstream-check in the linter repo.

**Comment by travier** [comment]
Thanks. https://github.com/flathub/flatpak-builder-lint/pull/63

**Comment by travier** [comment]
bot, build

**Comment by nicolasfella** [comment]
Is there anything else that needs to be done for the exception to apply?

**Comment by hfiguiere** [comment]
I that case what you need is to add the "skip-appstream-check" to the flathub.json. The exception is just meant to allow that option (that was previously no enforced).

**Comment by nicolasfella** [comment]
Yay, it builds now.

However it crashes on launch when an instance is already running

```
#0  0x00007ffff5c5949b in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5c42857 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff629db97 in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff629cfc2 in qt_assert(char const*, char const*, int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fffe876e4fd in ?? () from /usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5
#5  0x00007fffe876e76a in ?? () from /usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5
#6  0x00007fffe876df75 in ?? () from /usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5
#7  0x00007fffe876e00c in KWayland::Client::ConnectionThread::~ConnectionThread() () from /usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5
#8  0x00007fffe876e046 in KWayland::Client::ConnectionThread::~ConnectionThread() () from /usr/lib/x86_64-linux-gnu/libKF5WaylandClient.so.5
#9  0x00007fffebf9f710 in ?? () from /usr/lib/plugins/kf5/org.kde.kidletime.platforms/KF5IdleTimeKWaylandPlugin.so
#10 0x00007ffff7e92bf0 in ?? () from /usr/lib/x86_64-linux-gnu/libKF5IdleTime.so.5
#11 0x00007ffff7e92c56 in KIdleTime::~KIdleTime() () from /usr/lib/x86_64-linux-gnu/libKF5IdleTime.so.5
#12 0x00007ffff7e92d42 in ?? () from /usr/lib/x86_64-linux-gnu/libKF5IdleTime.so.5
#13 0x00007ffff5c5be2a in __run_exit_handlers () from /usr/lib/x86_64-linux-gnu/libc.so.6
#14 0x00007ffff5c5bfce in exit () from /usr/lib/x86_64-linux-gnu/libc.so.6
#15 0x00007ffff7f90be4 in ?? () from /usr/lib/x86_64-linux-gnu/libKF5DBusAddons.so.5
#16 0x00007ffff7f9122d in ?? () from /usr/lib/x86_64-linux-gnu/libKF5DBusAddons.so.5
#17 0x00007ffff7f8e184 in KDBusService::KDBusService(QFlags<KDBusService::StartupOption>, QObject*) () from /usr/lib/x86_64-linux-gnu/libKF5DBusAddons.so.5
#18 0x0000555555558406 in ?? ()
#19 0x00007ffff5c43b80 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#20 0x00005555555589de in ?? ()
```

**Comment by nicolasfella** [comment]
Now with 100% more debug symbols:

```
#1  0x00007ffff5c42857 in __GI_abort () at abort.c:79
#2  0x00007ffff629db97 in qt_message_fatal (message=<synthetic pointer>..., context=...) at global/qlogging.cpp:1914
#3  QMessageLogger::fatal (this=this@entry=0x7fffffffd028, msg=msg@entry=0x7ffff65af000 "ASSERT: \"%s\" in file %s, line %d") at global/qlogging.cpp:893
#4  0x00007ffff629cfc2 in qt_assert (assertion=assertion@entry=0x7fffe87c4861 "aalloc >= d->size", file=file@entry=0x7fffe87c4843 "/usr/include/QtCore/qvector.h", line=line@entry=692) at global/qglobal.cpp:3366
#5  0x00007fffe876e4fd in QVector<KWayland::Client::ConnectionThread*>::realloc (this=this@entry=0x7fffe87feb60 <KWayland::Client::ConnectionThread::Private::connections>, aalloc=<optimized out>, options=..., 
    options@entry=...) at /usr/include/QtCore/qvector.h:692
#6  0x00007fffe876e76a in QVector<KWayland::Client::ConnectionThread*>::detach (this=0x7fffe87feb60 <KWayland::Client::ConnectionThread::Private::connections>) at /usr/include/QtCore/qflags.h:121
#7  QVector<KWayland::Client::ConnectionThread*>::erase (this=this@entry=0x7fffe87feb60 <KWayland::Client::ConnectionThread::Private::connections>, abegin=..., aend=...) at /usr/include/QtCore/qvector.h:913
#8  0x00007fffe876df75 in QVector<KWayland::Client::ConnectionThread*>::remove (i=<optimized out>, this=0x7fffe87feb60 <KWayland::Client::ConnectionThread::Private::connections>)
    at /usr/include/QtCore/qvector.h:478
#9  QVector<KWayland::Client::ConnectionThread*>::removeOne (t=@0x5555556df638: 0x555555706200, this=0x7fffe87feb60 <KWayland::Client::ConnectionThread::Private::connections>)
    at /usr/include/QtCore/qvector.h:185
#10 KWayland::Client::ConnectionThread::Private::~Private (this=0x5555556df5f0, __in_chrg=<optimized out>) at /run/build-runtime/kwayland/src/client/connection_thread.cpp:75
#11 0x00007fffe876e00c in QScopedPointerDeleter<KWayland::Client::ConnectionThread::Private>::cleanup (pointer=0x5555556df5f0) at /usr/include/QtCore/qscopedpointer.h:52
#12 QScopedPointerDeleter<KWayland::Client::ConnectionThread::Private>::cleanup (pointer=0x5555556df5f0) at /usr/include/QtCore/qscopedpointer.h:52
#13 QScopedPointer<KWayland::Client::ConnectionThread::Private, QScopedPointerDeleter<KWayland::Client::ConnectionThread::Private> >::~QScopedPointer (this=0x555555706210, __in_chrg=<optimized out>)
    at /usr/include/QtCore/qscopedpointer.h:107
#14 KWayland::Client::ConnectionThread::~ConnectionThread (this=0x555555706200, __in_chrg=<optimized out>) at /run/build-runtime/kwayland/src/client/connection_thread.cpp:218
#15 0x00007fffe876e046 in KWayland::Client::ConnectionThread::~ConnectionThread (this=0x555555706200, __in_chrg=<optimized out>) at /run/build-runtime/kwayland/src/client/connection_thread.cpp:218
#16 0x00007fffebf9f710 in Poller::unloadPoller (this=0x555555709330) at /run/build-runtime/kwayland-integration/src/idletime/poller.cpp:132
#17 0x00007ffff7e92bf0 in KIdleTimePrivate::unloadCurrentSystem (this=0x5555556e25e0) at /run/build-runtime/kidletime/src/kidletime.cpp:272
#18 0x00007ffff7e92c56 in KIdleTime::~KIdleTime (this=0x5555557087c0, __in_chrg=<optimized out>) at /run/build-runtime/kidletime/src/kidletime.cpp:95
#19 0x00007ffff7e92d42 in KIdleTime::~KIdleTime (this=0x5555557087c0, __in_chrg=<optimized out>) at /run/build-runtime/kidletime/src/kidletime.cpp:92
#20 KIdleTimeHelper::~KIdleTimeHelper (this=<optimized out>, __in_chrg=<optimized out>) at /run/build-runtime/kidletime/src/kidletime.cpp:30
#21 (anonymous namespace)::Q_QGS_s_globalKIdleTime::Holder::~Holder (this=<optimized out>, __in_chrg=<optimized out>) at /run/build-runtime/kidletime/src/kidletime.cpp:37
#22 0x00007ffff5c5be2a in __run_exit_handlers (status=0, listp=0x7ffff5df5598 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#23 0x00007ffff5c5bfce in __GI_exit (status=<optimized out>) at exit.c:139
#24 0x00007ffff7f90be4 in Registration::attemptRegistration (this=this@entry=0x7fffffffd440) at /run/build-runtime/kdbusaddons/src/kdbusservice.cpp:244
#25 0x00007ffff7f9122d in Registration::registerOnBus (this=this@entry=0x7fffffffd440) at /run/build-runtime/kdbusaddons/src/kdbusservice.cpp:163
#26 0x00007ffff7f8e184 in Registration::run (this=0x7fffffffd440) at /run/build-runtime/kdbusaddons/src/kdbusservice.cpp:115
#27 KDBusService::KDBusService (this=<optimized out>, options=..., parent=<optimized out>) at /run/build-runtime/kdbusaddons/src/kdbusservice.cpp:287
#28 0x0000555555558406 in ?? ()
#29 0x00007ffff5c43b80 in __libc_start_main (main=0x555555557900, argc=1, argv=0x7fffffffd6c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd6b8)
    at ../csu/libc-start.c:332
#30 0x00005555555589de in ?? ()
```

**Comment by nicolasfella** [comment]
ASSERT: "aalloc >= d->size" in file /usr/include/QtCore/qvector.h, line 692

**Pull request closed without merging**
